name: Bug Report
labels: ["bug"]
title: "[Bug]: "
description: "Report a bug. Adding screentshots or short videos are highly encouraged!"
body:
  - type: dropdown
    attributes:
      label: Bug type
      description: Select the type of bugs you want to report.
      multiple: true
      options: 
        - Installation
        - Style 
        - Behaviour
    validations:
      required: true
  - type: input
    attributes:
      label: Commenter Version
      description: Provide the commenter version that you are using.
      placeholder: 2.0.5
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Mode
      description: Select the commenter mode you are using.
      multiple: false
      options: 
        - Auth
        - Guest 
        - Secured Guest
    validations:
      required: true    
  - type: input
    attributes:
      label: Database
      description: What is the database system.
      placeholder: mysql
  - type: textarea
    attributes:
      label: Description
      description: Provide a detailed description of the issue you are facing.
      placeholder: Write down the issue description clearly
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps To Reproduce
      description: Provide detailed steps to reproduce your issue (Issues submitted at this step are given higher priority).
      placeholder: |
        1. Folk the https://github.com/Lakshan-Madushanka/commenter-issue-reproducer repo
        2. Create a branch with issue no, eg: issue-20
        3. Reproduce the error
        3. Update the issue with the reproduced branch url in the following input field
  - type: input
    attributes:
      label: Reproduce URL
      description: Please enter your GitHub URL to provide a reproduction of the issue (Issues submitted at this step are given higher priority).
      placeholder: ex. https://github.com/Lakshan-Madushanka/commenter-issue-reproducer/tree/issue-100
